#!/bin/sh

PKGS_TO_REMOVE=(
    "midori"                # Lightweight web browser
    "parole"                # Modern media player based on the GStreamer framework
    "qpdfview"              # A tabbed PDF viewer using the poppler library
    "gnome-keyring"         # Stores passwords and encryption keys
    "seahorse"              # GNOME application for managing PGP keys.
    "evince"                # Document viewer
    "mousepad"              # Simple text editor for Xfce
)

PKGS_ALL=(
    # Development packages
    "git"                   # The fast distributed version control system
    "tig"                   # Text-mode interface for Git
    "ctags"                 # Generates an index file of language objects found in source files
    "clang"                 # C language family frontend for LLVM
    "python-pip"            # The PyPA recommended tool for installing Python packages
    "libpqxx"               # C++ client API for PostgreSQL
    "go"                    # Core compiler tools for the Go programming language

    # Fonts
    "terminus-font"         # Monospace bitmap font (for X11 and console)
    "ttf-font-awesome"      # Iconic font designed for Bootstrap

    # Themes & utils
    "qt5ct"                 # Qt5 Configuration Utility
    "qt6ct"                 # Qt 6 Configuration Utility

    # X-console utils
    "xorg-xrandr"           # Primitive command line interface to RandR extension
    "xorg-xev"              # Print contents of X events
    "xorg-xinput"           # Small commandline tool to configure devices
    "xorg-xprop"            # Property displayer for X
    "xorg-xwininfo"         # Command-line utility to print information about windows on an X server
    "xclip"                 # Command line interface to the X11 clipboard
    "numlockx"              # Turns on the numlock key in X11

    # Console utils
    "htop"                  # Interactive process viewer
    "unrar"                 # The RAR uncompression program
    "p7zip"                 # Command-line file archiver with high compression ratio
    "mc"                    # A file manager that emulates Norton Commander
    "grc"                   # Yet another colouriser for beautifying your
                            # logfiles or output of commands
    "rxvt-unicode"
    "fastfetch"              # A CLI system information tool written in BASH
                            # that supports displaying images.
    "trash-cli"             # Command line trashcan (recycle bin) interface
    "imagemagick"           # An image viewing/manipulation program

    # Network utils
    "wget"                  # Network utility to retrieve files from the Web
    "curl"                  # Command line tool and library for transferring data with URLs
    "w3m"                   # Text-based Web browser as well as pager
    "sshfs"                 # FUSE client based on the SSH File Transfer Protocol
    "net-tools"             # Configuration tools for Linux networking
    "dnsutils"              # A complete, highly portable implementation of the DNS protocol

    # Applications
    "gnome-calculator"      # GNOME Scientific calculator
    "keepassxc"             # Cross-platform community-driven port of Keepass
                            # password manager
    "gparted"               # A Partition Magic clone, frontend to GNU Parted
    "firefox"               # Standalone web browser from mozilla.org
    "telegram-desktop"      # Official Telegram Desktop client
    "transmission-qt"       # Fast, easy, and free BitTorrent client (GTK+ GUI)

    # Media
    "mpv"                   # Cross-platform media player
    "feh"                   # Fast and light imlib2-based image viewer
    "pulsemixer"            # CLI and curses mixer for pulseaudio
    "python-mutagen"        # An audio metadata tag reader and writer
                            # (python library)

    # Desktop & integration
    "xdg-desktop-portal"    # Desktop integration portals for sandboxed apps
    "xdg-desktop-portal-gtk"
    "xdg-dbus-proxy"        # Filtering proxy for D-Bus connections
    "xdg-utils"             # Command line tools that assist applications with
                            # a variety of desktop integration tasks
    "kvantum"               # SVG-based theme engine for Qt5/6

    "thunar"                # Modern, fast and easy-to-use file manager for Xfce
    "thunar-archive-plugin" # Adds archive operations to the Thunar file context menus
    "thunar-media-tags-plugin" # Adds special features for media files
    "thunar-volman"         # Automatic management of removable drives and media
    "thunarx-python"        # Thunarx Python Bindings
    "gtkhash-thunar"        # GtkHash extension for Thunar
    "tumbler"               # Thumbnail service implementing the thumbnail management D-Bus specification
    "engrampa"              # Archive manipulator

    "gvfs"                  # Virtual filesystem implementation for GIO
    "gvfs-afc"              # gvfs AFC backend; Apple mobile devices
    "gvfs-gphoto2"          # gvfs gphoto2 backend; PTP camera, MTP media player
    "gvfs-mtp"              # gvfs MTP backend; Android, media player
    "gvfs-nfs"              # gvfs NFS backend
    "gvfs-smb"              # gvfs SMB/CIFS backend; Windows client

    # WM & dependencies
    "bspwm"                 # Tiling window manager based on binary space partitioning
    "sxhkd"                 # Simple X hotkey daemon
    "rofi"                  # A window switcher, run dialog and dmenu replacement
    "polybar"               # A fast and easy-to-use status bar
    "dunst"                 # Customizable and lightweight notification-daemon
    "picom"                 # A lightweight compositor for X11

    # Any dependencies
    "lib32-freetype2"       # Font rasterization library (32-bit), requered for wine32

    # Dev
    #"python-setuptools"     # Easily download, build, install, upgrade, and uninstall Python packages
    #"ipython"               # Enhanced Interactive Python shell
)

echo -en "Remove preinstalled packages? [Y/n] "
read select
if [[ "${select:-Y}" =~ ^y|Y ]]; then
    for pkg in ${PKGS_TO_REMOVE[*]}; do
        sudo pacman -R $pkg
    done
fi

echo -en "Install base development meta-package? [Y/n] "
read select
[[ "${select:-Y}" =~ ^y|Y ]] \
    && sudo pacman -S base-devel

echo -en "Install packages? [Y/n] "
read select
[[ "${select:-Y}" =~ ^y|Y ]] \
    && sudo pacman -S ${PKGS_ALL[*]} --needed

echo -en "Run post-install scripts? [Y/n] "
read select
if [[ "${select:-Y}" =~ ^y|Y ]]; then
    xdg-mime default thunar.desktop inode/directory
    echo "add 'export GTK_USE_PORTAL=0' to profile"
fi
