#!/bin/sh

REMOVE=(
    "midori"                # Lightweight web browser
    "parole"                # Modern media player based on the GStreamer framework
    "qpdfview"              # A tabbed PDF viewer using the poppler library
    "gnome-keyring"         # Stores passwords and encryption keys
    "seahorse"              # GNOME application for managing PGP keys.
    "evince"                # Document viewer 
    "mousepad"              # Simple text editor for Xfce
)

LIST=(
    # Development packages
    "git"
    "tig"
    "ctags"
    "clang"
    "python-pip"
    "libpqxx"
    "go"

    # Fonts
    "terminus-font"
    "ttf-font-awesome"

    # Themes & utils
    "qt5ct"                 # Qt5 Configuration Utility
    "qt6ct"                 # Qt 6 Configuration Utility

    # X-console utils
    "xorg-xrandr"
    "xorg-xev"
    "xorg-xinput"
    "xorg-xprop"            # Property displayer for X
    "xorg-xwininfo"         # Command-line utility to print information about windows on an X server
    "xclip"                 # Command line interface to the X11 clipboard
    "numlockx"              # Turns on the numlock key in X11

    # Console utils
    "htop"
    "unrar"
    "p7zip"
    "mc"
    "grc"                   # Yet another colouriser for beautifying your
                            # logfiles or output of commands
    "rxvt-unicode"
    "neofetch"              # A CLI system information tool written in BASH
                            # that supports displaying images.
    "trash-cli"             # Command line trashcan (recycle bin) interface
    "imagemagick"           # An image viewing/manipulation program

    # Network utils
    "wget"
    "curl"
    "w3m"
    "sshfs"
    "net-tools"             # Configuration tools for Linux networking
    "dnsutils"              # A complete, highly portable implementation of the DNS protocol

    # Applications
    "gnome-calculator"      # GNOME Scientific calculator
    "keepassxc"             # Cross-platform community-driven port of Keepass 
                            # password manager
    "gparted"               # A Partition Magic clone, frontend to GNU Parted

    "xdg-desktop-portal"    # Desktop integration portals for sandboxed apps
    "xdg-desktop-portal-gtk"

    "firefox"
    "telegram-desktop"
    "transmission-gtk"

    # Media
    "mpv"                   # Cross-platform media player
    "feh"                   # Fast and light imlib2-based image viewer
    "pulsemixer"            # CLI and curses mixer for pulseaudio
    "python-mutagen"        # An audio metadata tag reader and writer
                            # (python library)

    # WM & dependencies
    "bspwm"                 # Tiling window manager based on binary space partitioning
    "picom"                 # X compositor that may fix tearing issues
    "sxhkd"                 # Simple X hotkey daemon
    "rofi"                  # A window switcher, run dialog and dmenu replacement
    "polybar"               # A fast and easy-to-use status bar
    "dunst"                 # Customizable and lightweight notification-daemon
)

echo -en "Remove preinstalled packages? [y/N] "
read select
if [[ "Y|y" == *"${select:-N}"* ]]; then
    for pkg in ${REMOVE[*]}; do
        sudo pacman -R $pkg
    done
fi

echo -en "Install base development meta-package? [Y/n] "
read select
[[ "Y|y" == *"${select:-N}"* ]] \
    && sudo pacman -S base-devel

echo -en "Install packages? [Y/n] "
read select
[[ "Y|y" == *"${select:-Y}"* ]] \
    && sudo pacman -S ${LIST[*]} --needed
