#!/bin/sh

DATA=$(cat <<- ENDDATA
[Unit]
Description=SSH key agent

[Service]
Type=simple
Environment=SSH_AUTH_SOCK=%t/ssh-agent.socket
# DISPLAY required for ssh-askpass to work
Environment=DISPLAY=:0
ExecStart=/usr/bin/ssh-agent -D -a \$SSH_AUTH_SOCK

[Install]
WantedBy=default.target
ENDDATA
)

DEST="$HOME/.config/systemd/user/ssh-agent.service"

mkdir -p "$(dirname "$DEST")" > /dev/null 2>&1
echo  -e "${DATA}" > "$DEST"

echo "Add environment to profile:"
echo "export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket"

systemctl --user daemon-reload
systemctl --user enable --now ssh-agent
systemctl --user status ssh-agent
