#!/bin/sh

CONF="$(dirname "${0/\~/$HOME}")/resources"

echo -e "Remove previous configuration..."
rm -rf $HOME/.vim/ > /dev/null 2>&1

if ! which gvim > /dev/null; then
	echo -e "Install 'gvim' package..."
	sudo pacman -S gvim --needed || exit 1
fi


if [ ! -e ~/.vimrc ]; then
    echo "Copy .vimrc file..."
    cp -xarf "$CONF/.vimrc" "$HOME/.vimrc" || exit 1
fi

echo  -e "Install plugin manager..."
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim || exit 1

echo -e "Install vim plugins..."
vim --not-a-term +PlugInstall
