#!/bin/sh

CONF="$(dirname "${0/\~/$HOME}")/resources"

if [[ "${SHELL}" == */zsh ]]; then
    echo -e "Shell zsh already installed!"
    exit 0
fi

if ! which zsh > /dev/null; then
	echo -e "Install 'zsh' package..."
    sudo pacman -S zsh --needed || exit 1
fi

if [ ! -e ~/.zshrc ]; then
    echo "Copy .zshrc file..."
    cp -xarf "$CONF/.zshrc" "$HOME/.zshrc" || exit 1
fi

chsh -s "$(which zsh)"
