#!/usr/bin/env bash
# 

BASE="$(dirname "${0/\~/$HOME}")"

# install requered linux headers
$BASE/kernel-headers

echo -e "$(printf '─%.0s' {1..72})"
echo -e "\033[33mInstall the required driver dependencies\033[0m"

sudo pacman -S bc dkms git base-devel --needed

echo -e "$(printf '─%.0s' {1..72})"
echo -e "\033[33mInstall nvidia-dkms drivers\033[0m"

sudo pacman -S nvidia-dkms nvidia-utils --needed

