#!/bin/sh

SERVICE="/etc/systemd/swap.conf.d"

CONFIG=$(cat <<- ENDCONFIG
# See swap.conf(5) and /usr/share/systemd-swap/swap-default.conf for details.

zswap_enabled=0
zram_enabled=1
swapfc_enabled=1
ENDCONFIG
)


sudo pacman -S systemd-swap --needed

sudo mkdir -p "${SERVICE}" > /dev/null 2>&1
sudo /bin/sh -c "echo -e \"${CONFIG}\" > ${SERVICE}/zswap.conf"

sudo systemctl daemon-reload
sudo systemctl enable systemd-swap
sudo systemctl restart systemd-swap

systemctl status systemd-swap
