#!/bin/sh

CONF="$(dirname "${0/\~/$HOME}")/share"

if [[ "${SHELL}" == */zsh ]]; then
    echo -e "\033[32mzsh already installed!\033[0m"
    exit 1
fi

echo -e "Install packages"
sudo pacman -S zsh --needed

echo -e "Copy config files..."

if cp -xarf "$CONF/zshrc" "$HOME/.zshrc"; then
    echo -e "OK"
else
    echo -e "\033[31mFile '.vimrc' is not copyed!!!\033[0m"
    exit 1
fi

echo -e "Change shell to '/bin/zsh'"
chsh -s /bin/zsh \
    && echo -e "\033[32m  completed\033[0m"
