#!/bin/sh

# using as library?
[[ "${0}" != "${BASH_SOURCE}" ]] && \
    BASE_IS_LIB=true || BASE_IS_LIB=

NOFORCE="--needed"
_ALL=True


isinstalled() {
    [[ $(ls /var/lib/pacman/local | grep -E "^${1}-[0-9]+.*$") ]] \
        && return 0
    return 1
}

remove() {
    local LIST

    for i in ${@}; do
        isinstalled "$i" && LIST="$LIST $i"
    done

    [[ ! "$LIST" ]] && return

    echo -e "$LIST"
    echo -n "Remove? [Y/n] "
    read select

    [[ "Y|y" == *"${select:-Y}"* ]] \
        && sudo pacman --remove $LIST
}

install() {
    local ISAUR LIST

    if [[ "$1" == "--aur" ]]; then
        ISAUR=true; shift
    fi

    if [[ "$NOFORCE" ]]; then
        for i in ${@}; do
            isinstalled "$i" || LIST="$LIST $i"
        done
    else
        LIST="${@}"
    fi

    [[ ! "$LIST" ]] && return

    echo -e "$LIST"
    echo -n "Install? [Y/n] "
    read select

    if [[ "Y|y" == *"${select:-Y}"* ]]; then
        if [[ "$ISAUR" ]]; then
            pamac install $LIST
        else
            sudo pacman -S $LIST $NOFORCE
        fi
    fi
}


REMOVE=(
    "midori"                # Lightweight web browser
    "parole"                # Modern media player based on the GStreamer framework
    "qpdfview"              # A tabbed PDF viewer using the poppler library
    "gnome-keyring"         # Stores passwords and encryption keys
    "seahorse"              # GNOME application for managing PGP keys.
    "evince"                # Document viewer 
)

MAIN=(
    # Development packages
    "git"
    "tig"
    "ctags"
    "clang"
    "python-pip"
    "libpqxx"
    "go"
    "jq"

    # Fonts
    "terminus-font"
    "ttf-font-awesome"
    #"ttf-polybar-icons"

    # Icons-themes

    # Themes & utils
    "gtk-engine-murrine"    # GTK2 engine to make your desktop look like a 'murrina'
    "qt5ct"                 # Qt5 Configuration Utility
    "qt6ct"                 # Qt 6 Configuration Utility

    # Utils
    "xorg-xrandr"
    "xorg-xev"
    "xorg-xinput"
    "xorg-xprop"            # Property displayer for X
    "xorg-xwininfo"         # Command-line utility to print information about windows on an X server

    "xautomation"
    "xdotool"
    "xclip"                 # Command line interface to the X11 clipboard
    "xsettingsd"            # Provides settings to X11 applications via the
                            # XSETTINGS specification
    "brightnessctl"         # Lightweight brightness control tool

    "xdg-desktop-portal"    # Desktop integration portals for sandboxed apps
    "xdg-desktop-portal-gtk"

    "numlockx"              # Turns on the numlock key in X11
    #"exfat-utils"
    "htop"
    "gtop"
    "powertop"
    "zsh"
    "unrar"
    "p7zip"
    "mc"
    "tmux"    
    "hddtemp"
    "smartmontools"
    "grc"                   # Yet another colouriser for beautifying your
                            # logfiles or output of commands

    "rxvt-unicode"

    "gnome-calculator"      # GNOME Scientific calculator
    "keepassxc"             # Cross-platform community-driven port of Keepass 
                            # password manager

    "trash-cli"             # Command line trashcan (recycle bin) interface
    "ncdu"                  # Disk usage analyzer with an ncurses interface
    "imagemagick"           # An image viewing/manipulation program
    "mousepad"              # Simple text editor for Xfce
    "gparted"               # A Partition Magic clone, frontend to GNU Parted
    "zathura"               # Minimalistic document viewer

    # Network
    "wget"
    "curl"
    "w3m"
    "httpie"                # cURL for humans
    "websocat"              # Command-line client for web sockets, like 
                            # netcat/curl/socat for ws://
    "net-tools"             # Configuration tools for Linux networking
    "sshfs"
    "dnsutils"              # A complete, highly portable implementation of the DNS protocol

    "firefox"
    "telegram-desktop"
    #"transmission-gtk"

    # Media
    "mpv"                   # Cross-platform media player
    "feh"                   # Fast and light imlib2-based image viewer
    "pulsemixer"            # CLI and curses mixer for pulseaudio
    "python-mutagen"        # An audio metadata tag reader and writer
                            # (python library)

    # WM & dependencies
    "bspwm"                 # Tiling window manager based on binary space partitioning
    "picom"                 # X compositor that may fix tearing issues
    "sxhkd"                 # Simple X hotkey daemon
    "rofi"                  # A window switcher, run dialog and dmenu replacement
    "polybar"               # A fast and easy-to-use status bar
    "dunst"                 # Customizable and lightweight notification-daemon
    #"conky"                 # An advanced system monitor for X based on torsmo 
)

AUR=(
    # Themes & utils
    "qt5-styleplugins"      # Additional style plugins for Qt5
    "qt6gtk2"               # GTK+2.0 integration plugins for Qt6 (AUR)

    # Fonts
    "ttf-iosevka-fixed-curly"
    "ttf-symbola"

    # Extra
    #"g810-led-git"          # Linux led controller for Logitech G213, G410,
                            # G413, G512, G513, G610, G810, G815, G910 and 
                            # GPRO Keyboards
)


# -----------------------------------------------------------------------------
[[ ${BASE_IS_LIB} ]] && return # run as a library
# -----------------------------------------------------------------------------

BASE="$(dirname "${BASH_SOURCE:-$0}")"


while [ -n "$1" ]; do
    case "${1}" in
    --force)
        NOFORCE=
        ;;
    --remove)
        _ALL=
        _REMOVE=YES
        ;;
    --base)
        _ALL=
        _BASE=YES
        ;;
    --main)
        _ALL=
        _MAIN=YES
        ;;
    --aur)
        _ALL=
        _AUR=YES
        ;;
    --all)
        _ALL=YES
        ;;
    --help)
        ;;
    esac
    shift
done


if [[ "$_ALL" || "$_REMOVE" ]]; then
    echo -e "Remove preinstalled packages:"
    remove ${REMOVE[@]}
fi


if [[ "$_ALL" || "$_BASE" ]]; then
    echo -en "Install base development meta-package? [y/N] "
    read select

    [[ "Y|y" == *"${select:-N}"* ]] \
        && sudo pacman -S base-devel $NOFORCE
fi


if [[ "$_ALL" || "$_MAIN" ]]; then
    echo -e "Install packages:"
    install ${MAIN[@]}
fi

if [[ "$_ALL" || "$_AUR" ]]; then
    echo -e "Install AUR packages:"
    install --aur ${AUR[@]}
fi

