#!/usr/bin/env bash
# 

isinstalled() {
    [[ $(ls /var/lib/pacman/local | grep -E "^${1}-[0-9]+.*$") ]] \
        && return 0
    return 1
}

_headers=(
    $(pacman -Qsq "^linux" | grep "^linux[0-9]*[-rt]*$" | awk '{print $1"-headers"}' ORS=' ')
)

if [[ ${#_headers[@]} -eq 0 ]]; then
    echo -e "\033[31mHeaders information not found!\033[0m"
    exit 1
fi

echo -e "\033[33mFound required linux headers: ${_headers[@]}\033[0m"

headers=()

for h in ${_headers[@]}; do
    if [[ ! $(pacman -Ss $h) ]]; then
        echo -en "\033[31mPackage $h not found\033[0m"
        echo -e  "\033[31m, maybe you need to remove the kernel\033[0m"
        exit 1
    fi

    isinstalled $h \
        || headers+=( $h )
done

if [[ ${#headers[@]} -gt 0 ]]; then
    echo -en "Install required linux headers? [Y/n] "
    read select

    [[ "Y|y" == *"${select:-Y}"* ]] \
        && sudo pacman -S ${headers[@]} --needed
fi
