#!/usr/bin/env bash
# 
# https://archived.forum.manjaro.org/t/solved-rtl8811au-how-to-install-the-wifi-driver-properly/145736/6
# https://wiki.archlinux.org/title/Network_configuration_(%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9)/Wireless_(%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9)#rtl88xxau
#

_headers=(
    $(pacman -Qsq "^linux" | grep "^linux[0-9]*[-rt]*$" | awk '{print $1"-headers"}' ORS=' ')
)

[[ ${#_headers[@]} -eq 0 ]] && \
    echo -e "\033[31mHeaders information not found!\033[0m" && \
    exit 1

echo -e "\033[33mInstalling the required linux headers: ${_headers[@]}\033[0m"

headers=()

for h in ${_headers[@]}; do
    [[ ! $(pacman -Ss $h) ]] && \
        echo -en "\033[31mPackage $h not found\033[0m" && \
        echo -e  "\033[31m, maybe you need to remove the kernel\033[0m" && \
        exit 1

    headers+=( $h )
done

sudo pacman -S ${headers[@]} --needed

echo -e "$(printf '─%.0s' {1..72})"
echo -e "\033[33mInstall pamac-cli along with the required driver dependencies\033[0m"

sudo pacman -S bc dkms git base-devel pamac-cli --needed

echo -e "$(printf '─%.0s' {1..72})"
echo -e "\033[33mInstall the driver for the rtl8811au adapter from the AUR\033[0m"
echo -e "\033[33mhttps://github.com/aircrack-ng/rtl8812au\033[0m"

pamac build rtl88xxau-aircrack-dkms-git

echo -e "$(printf '─%.0s' {1..72})"
echo -e "\033[33mUnblock all network adapters\033[0m"

sudo rfkill unblock all


echo -e "$(printf '─%.0s' {1..72})"
echo -e "\033[32mLED control:

statically by module parameter in /etc/modprobe.d/88XXau.conf or wherever,
for example:
    options 88XXau rtw_led_ctrl=0
value can be 0 or 1

or dynamically by writing to /proc/net/rtl88XXau/\$(interface name)/led_ctrl,
for example:
    $ echo 0 > /proc/net/rtl88XXau/\$(interface name)/led_ctrl
value can be 0 or 1

check current value:
    $ cat /proc/net/rtl88XXau/\$(interface name)/led_ctrl
\033[0m"
